import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <main className="bg-background">
          <div className="flex flex-col justify-center gap-2 p-8">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
