import type { Metadata } from "next";
import "./globals.css";
import { NavMenu } from "@/components/layout/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <main className="bg-background">
          <NavMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
